// Code generated by "gends"; DO NOT EDIT.

package list // import "kkn.fi/list"

// Complex128List holds an ordered collection of complex128's.
type Complex128List struct {
	values []complex128
}

// NewComplex128 creates an empty list of Complex128List's.
func NewComplex128() *Complex128List {
	return &Complex128List{}
}

// NewComplex128With creates a list of Complex128List's filled with given
// values.
func NewComplex128With(values ...complex128) *Complex128List {
	return &Complex128List{
		values: values,
	}
}

// Equals checks list equality given other list. In order to be equal both lists
// must be of same type.
func (l *Complex128List) Equals(other interface{}) bool {
	list, ok := other.(*Complex128List)
	if !ok {
		return false
	}
	if len(l.values) != len(list.values) {
		return false
	}
	for i, v := range list.Slice() {
		if v != l.values[i] {
			return false
		}
	}
	return true

}

// Add appends a value to the end of the list.
func (l *Complex128List) Add(value complex128) {
	l.values = append(l.values, value)
}

// AddAll appends all given values to the end of the list.
func (l *Complex128List) AddAll(values ...complex128) {
	l.values = append(l.values, values...)
}

// Get returns the complex128 element at given index.
func (l *Complex128List) Get(index int) complex128 {
	return l.values[index]
}

// Len returns the size of the list.
func (l *Complex128List) Len() int {
	return len(l.values)
}

// IsEmpty return true if list is empty, false otherwise.
func (l *Complex128List) IsEmpty() bool {
	return len(l.values) == 0
}

// Contains returns true if given value is contained by the list, false
// otherwise.
func (l *Complex128List) Contains(value complex128) bool {
	for _, v := range l.values {
		if v == value {
			return true
		}
	}
	return false
}

// Slice returns complex128 slice of the elements contained within the list.
func (l *Complex128List) Slice() []complex128 {
	return l.values
}

// Remove deletes the given value from the list. Returns true if the list
// contained specified value, false otherwise.
func (l *Complex128List) Remove(value complex128) bool {
	for i, v := range l.values {
		if v == value {
			l.values = append(l.values[:i], l.values[i+1:]...)
			return true
		}
	}
	return false
}
