// Code generated by "gends"; DO NOT EDIT.

package list // import "kkn.fi/list"

// Float64 holds an ordered collection of float64's.
type Float64 struct {
	values []float64
}

// NewFloat64 creates an empty list of Float64's.
func NewFloat64() *Float64 {
	return &Float64{}
}

// NewFloat64With creates a list of Float64's filled with given
// values.
func NewFloat64With(values ...float64) *Float64 {
	return &Float64{
		values: values,
	}
}

// Equals checks list equality given other list. In order to be equal both lists
// must be of same type.
func (l *Float64) Equals(other interface{}) bool {
	list, ok := other.(*Float64)
	if !ok {
		return false
	}
	if len(l.values) != len(list.values) {
		return false
	}
	for i, v := range list.Slice() {
		if v != l.values[i] {
			return false
		}
	}
	return true

}

// Add appends a value to the end of the list.
func (l *Float64) Add(value float64) {
	l.values = append(l.values, value)
}

// AddAll appends all given values to the end of the list.
func (l *Float64) AddAll(values ...float64) {
	l.values = append(l.values, values...)
}

// Get returns the float64 element at given index.
func (l *Float64) Get(index int) float64 {
	return l.values[index]
}

// Len returns the size of the list.
func (l *Float64) Len() int {
	return len(l.values)
}

// IsEmpty return true if list is empty, false otherwise.
func (l *Float64) IsEmpty() bool {
	return len(l.values) == 0
}

// Contains returns true if given value is contained by the list, false
// otherwise.
func (l *Float64) Contains(value float64) bool {
	for _, v := range l.values {
		if v == value {
			return true
		}
	}
	return false
}

// Slice returns float64 slice of the elements contained within the list.
func (l *Float64) Slice() []float64 {
	return l.values
}

// Remove deletes the given value from the list. Returns true if the list
// contained specified value, false otherwise.
func (l *Float64) Remove(value float64) bool {
	for i, v := range l.values {
		if v == value {
			l.values = append(l.values[:i], l.values[i+1:]...)
			return true
		}
	}
	return false
}
