// Code generated by "gends"; DO NOT EDIT.

package list // import "kkn.fi/list"

// IntList holds an ordered collection of int's.
type IntList struct {
	values []int
}

// NewInt creates an empty list of IntList's.
func NewInt() *IntList {
	return &IntList{}
}

// NewIntWith creates a list of IntList's filled with given
// values.
func NewIntWith(values ...int) *IntList {
	return &IntList{
		values: values,
	}
}

// Equals checks list equality given other list. In order to be equal both lists
// must be of same type.
func (l IntList) Equals(other interface{}) bool {
	list, ok := other.(*IntList)
	if !ok {
		return false
	}
	if len(l.values) != len(list.values) {
		return false
	}
	for i, v := range list.Slice() {
		if v != l.values[i] {
			return false
		}
	}
	return true

}

// Add appends a value to the end of the list.
func (l *IntList) Add(value int) {
	l.values = append(l.values, value)
}

// AddAll appends all given values to the end of the list.
func (l *IntList) AddAll(values ...int) {
	l.values = append(l.values, values...)
}

// Get returns the int element at given index.
func (l IntList) Get(index int) int {
	return l.values[index]
}

// Len returns the size of the list.
func (l IntList) Len() int {
	return len(l.values)
}

// IsEmpty return true if list is empty, false otherwise.
func (l IntList) IsEmpty() bool {
	return len(l.values) == 0
}

// Contains returns true if given value is contained by the list, false
// otherwise.
func (l IntList) Contains(value int) bool {
	for _, v := range l.values {
		if v == value {
			return true
		}
	}
	return false
}

// Slice returns int slice of the elements contained within the list.
func (l IntList) Slice() []int {
	result := make([]int, 0, len(l.values))
	result = append(result, l.values...)
	return result
}

// Remove deletes the given value from the list. Returns true if the list
// contained specified value, false otherwise.
func (l *IntList) Remove(value int) bool {
	for i, v := range l.values {
		if v == value {
			l.values = append(l.values[:i], l.values[i+1:]...)
			return true
		}
	}
	return false
}
