// Code generated by "gends"; DO NOT EDIT.

package list // import "kkn.fi/list"

// Int16List holds an ordered collection of int16's.
type Int16List struct {
	values []int16
}

// NewInt16 creates an empty list of Int16List's.
func NewInt16() *Int16List {
	return &Int16List{}
}

// NewInt16With creates a list of Int16List's filled with given
// values.
func NewInt16With(values ...int16) *Int16List {
	return &Int16List{
		values: values,
	}
}

// Equals checks list equality given other list. In order to be equal both lists
// must be of same type.
func (l Int16List) Equals(other interface{}) bool {
	list, ok := other.(*Int16List)
	if !ok {
		return false
	}
	if len(l.values) != len(list.values) {
		return false
	}
	for i, v := range list.Slice() {
		if v != l.values[i] {
			return false
		}
	}
	return true

}

// Add appends a value to the end of the list.
func (l *Int16List) Add(value int16) {
	l.values = append(l.values, value)
}

// AddAll appends all given values to the end of the list.
func (l *Int16List) AddAll(values ...int16) {
	l.values = append(l.values, values...)
}

// Get returns the int16 element at given index.
func (l Int16List) Get(index int) int16 {
	return l.values[index]
}

// Len returns the size of the list.
func (l Int16List) Len() int {
	return len(l.values)
}

// IsEmpty return true if list is empty, false otherwise.
func (l Int16List) IsEmpty() bool {
	return len(l.values) == 0
}

// Contains returns true if given value is contained by the list, false
// otherwise.
func (l Int16List) Contains(value int16) bool {
	for _, v := range l.values {
		if v == value {
			return true
		}
	}
	return false
}

// Slice returns int16 slice of the elements contained within the list.
func (l Int16List) Slice() []int16 {
	result := make([]int16, 0, len(l.values))
	result = append(result, l.values...)
	return result
}

// Remove deletes the given value from the list. Returns true if the list
// contained specified value, false otherwise.
func (l *Int16List) Remove(value int16) bool {
	for i, v := range l.values {
		if v == value {
			l.values = append(l.values[:i], l.values[i+1:]...)
			return true
		}
	}
	return false
}
