// Code generated by "gends"; DO NOT EDIT.

package list // import "kkn.fi/list"

// StringList holds an ordered collection of string's.
type StringList struct {
	values []string
}

// NewString creates an empty list of StringList's.
func NewString() *StringList {
	return &StringList{}
}

// NewStringWith creates a list of StringList's filled with given
// values.
func NewStringWith(values ...string) *StringList {
	return &StringList{
		values: values,
	}
}

// Equals checks list equality given other list. In order to be equal both lists
// must be of same type.
func (l StringList) Equals(other interface{}) bool {
	list, ok := other.(*StringList)
	if !ok {
		return false
	}
	if len(l.values) != len(list.values) {
		return false
	}
	for i, v := range list.Slice() {
		if v != l.values[i] {
			return false
		}
	}
	return true

}

// Add appends a value to the end of the list.
func (l *StringList) Add(value string) {
	l.values = append(l.values, value)
}

// AddAll appends all given values to the end of the list.
func (l *StringList) AddAll(values ...string) {
	l.values = append(l.values, values...)
}

// Get returns the string element at given index.
func (l StringList) Get(index int) string {
	return l.values[index]
}

// Len returns the size of the list.
func (l StringList) Len() int {
	return len(l.values)
}

// IsEmpty return true if list is empty, false otherwise.
func (l StringList) IsEmpty() bool {
	return len(l.values) == 0
}

// Contains returns true if given value is contained by the list, false
// otherwise.
func (l StringList) Contains(value string) bool {
	for _, v := range l.values {
		if v == value {
			return true
		}
	}
	return false
}

// Slice returns string slice of the elements contained within the list.
func (l StringList) Slice() []string {
	result := make([]string, 0, len(l.values))
	result = append(result, l.values...)
	return result
}

// Remove deletes the given value from the list. Returns true if the list
// contained specified value, false otherwise.
func (l *StringList) Remove(value string) bool {
	for i, v := range l.values {
		if v == value {
			l.values = append(l.values[:i], l.values[i+1:]...)
			return true
		}
	}
	return false
}
