// Code generated by "gends"; DO NOT EDIT.

package list // import "kkn.fi/list"

// UintList holds an ordered collection of uint's.
type UintList struct {
	values []uint
}

// NewUint creates an empty list of UintList's.
func NewUint() *UintList {
	return &UintList{}
}

// NewUintWith creates a list of UintList's filled with given
// values.
func NewUintWith(values ...uint) *UintList {
	return &UintList{
		values: values,
	}
}

// Equals checks list equality given other list. In order to be equal both lists
// must be of same type.
func (l UintList) Equals(other interface{}) bool {
	list, ok := other.(*UintList)
	if !ok {
		return false
	}
	if len(l.values) != len(list.values) {
		return false
	}
	for i, v := range list.Slice() {
		if v != l.values[i] {
			return false
		}
	}
	return true

}

// Add appends a value to the end of the list.
func (l *UintList) Add(value uint) {
	l.values = append(l.values, value)
}

// AddAll appends all given values to the end of the list.
func (l *UintList) AddAll(values ...uint) {
	l.values = append(l.values, values...)
}

// Get returns the uint element at given index.
func (l UintList) Get(index int) uint {
	return l.values[index]
}

// Len returns the size of the list.
func (l UintList) Len() int {
	return len(l.values)
}

// IsEmpty return true if list is empty, false otherwise.
func (l UintList) IsEmpty() bool {
	return len(l.values) == 0
}

// Contains returns true if given value is contained by the list, false
// otherwise.
func (l UintList) Contains(value uint) bool {
	for _, v := range l.values {
		if v == value {
			return true
		}
	}
	return false
}

// Slice returns uint slice of the elements contained within the list.
func (l UintList) Slice() []uint {
	result := make([]uint, 0, len(l.values))
	result = append(result, l.values...)
	return result
}

// Remove deletes the given value from the list. Returns true if the list
// contained specified value, false otherwise.
func (l *UintList) Remove(value uint) bool {
	for i, v := range l.values {
		if v == value {
			l.values = append(l.values[:i], l.values[i+1:]...)
			return true
		}
	}
	return false
}
